/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package powernotes.pat;

/**
 *
 * @author Maxwell SSD
 */
public class addGame extends javax.swing.JFrame {

    /**
     * Creates new form addGame
     */
    public addGame() {
        initComponents();
    }
    
    private String gameName, platform;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackplate = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        cmbPlatform = new javax.swing.JComboBox<>();
        lblPlatform = new javax.swing.JLabel();
        lblGameName = new javax.swing.JLabel();
        txfGameName = new javax.swing.JTextField();
        btnAddGame = new javax.swing.JButton();
        lblHelp = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblAddAGame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelBackplate.setBackground(new java.awt.Color(50, 116, 220));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbPlatform.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbPlatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "XBOX", "PS4", "Nintendo", "Mobile" }));

        lblPlatform.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlatform.setText("Platform:");

        lblGameName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGameName.setText("Game:");

        txfGameName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfGameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGameNameActionPerformed(evt);
            }
        });

        btnAddGame.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddGame.setText("Add Game");
        btnAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGameActionPerformed(evt);
            }
        });

        lblHelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHelp.setText("Help");

        btnHelp.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblAddAGame.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblAddAGame.setText("Add a game");

        javax.swing.GroupLayout jPanelBackplateLayout = new javax.swing.GroupLayout(jPanelBackplate);
        jPanelBackplate.setLayout(jPanelBackplateLayout);
        jPanelBackplateLayout.setHorizontalGroup(
            jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackplateLayout.createSequentialGroup()
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackplateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(lblAddAGame))
                    .addGroup(jPanelBackplateLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBackplateLayout.createSequentialGroup()
                                .addComponent(lblGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txfGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBackplateLayout.createSequentialGroup()
                                .addComponent(lblPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPlatform, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackplateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHelp)
                    .addGroup(jPanelBackplateLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblHelp)))
                .addGap(33, 33, 33))
        );
        jPanelBackplateLayout.setVerticalGroup(
            jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackplateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddAGame, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlatform))
                .addGap(29, 29, 29)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGameName)
                    .addComponent(txfGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackplateLayout.createSequentialGroup()
                        .addComponent(btnAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackplateLayout.createSequentialGroup()
                        .addComponent(btnHelp)
                        .addGap(9, 9, 9)
                        .addComponent(lblHelp)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose(); //close this screen
    }//GEN-LAST:event_btnBackActionPerformed

    private void txfGameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGameNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGameNameActionPerformed

    private void btnAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGameActionPerformed
        //Collect data from components
        gameName = txfGameName.getText();
        platform = (String)cmbPlatform.getSelectedItem();
        
        //Send variables to SQLSTatments class to add game to database
        SQLSTatements bb = new SQLSTatements();
        bb.AddGame(gameName, platform);
        this.dispose(); //close screen

    }//GEN-LAST:event_btnAddGameActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        //Create help box (using message number 6)
        Help h = new Help(6);
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGame;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JComboBox<String> cmbPlatform;
    private javax.swing.JPanel jPanelBackplate;
    private javax.swing.JLabel lblAddAGame;
    private javax.swing.JLabel lblGameName;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JTextField txfGameName;
    // End of variables declaration//GEN-END:variables
}
