/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package powernotes.pat;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell SSD
 */
public class createReview extends javax.swing.JFrame {
    
    private GameArray ga = new GameArray(); //create GameArray object
    private Game[] gArray = ga.getDistArray(); //get array of distinct game names
    private int size = ga.getDistSize(); //get size of this array
    
    private Game[] fullArray = ga.getgArray(); //get array of all games
    private int fullSize = ga.getSize(); //get size of this array

    private int uID = 0; //initialise uID to 0 for debugging purposes.
    
    
    /**
     * Creates new form createReview
     */
    public createReview()
    {
        initComponents();
        for (int i = 0; i < size; i++)
            cmbGame.addItem(gArray[i].getName()); //populate game combo box
    }

        public createReview(int u)
    {
        uID = u;
        initComponents();
        for (int i = 0; i < size; i++)
            cmbGame.addItem(gArray[i].getName()); //populate game combo box
    }
    
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackplate = new javax.swing.JPanel();
        lblCreateAReview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaComment = new javax.swing.JTextArea();
        cmbPlatform = new javax.swing.JComboBox<>();
        cmbGame = new javax.swing.JComboBox<>();
        cmbRating = new javax.swing.JComboBox<>();
        btnNewGame = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPostReview = new javax.swing.JButton();
        lblGame = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        lblPlatform = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblComment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelBackplate.setBackground(new java.awt.Color(102, 102, 198));

        lblCreateAReview.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCreateAReview.setText("Create a review");

        txaComment.setColumns(20);
        txaComment.setRows(5);
        jScrollPane1.setViewportView(txaComment);

        cmbPlatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "XBOX", "PS4", "Nintendo", "Mobile" }));

        cmbGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Not selected)" }));
        cmbGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGameActionPerformed(evt);
            }
        });

        cmbRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cmbRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRatingActionPerformed(evt);
            }
        });

        btnNewGame.setText("Can't find your game? Add a new game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnPostReview.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPostReview.setText("Post review");
        btnPostReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostReviewActionPerformed(evt);
            }
        });

        lblGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGame.setText("Game:");

        lblRating.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRating.setText("Stars Rating:");

        lblPlatform.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlatform.setText("Platform:");

        lblHelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHelp.setText("Help");

        btnHelp.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblComment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblComment.setText("Comment:");

        javax.swing.GroupLayout jPanelBackplateLayout = new javax.swing.GroupLayout(jPanelBackplate);
        jPanelBackplate.setLayout(jPanelBackplateLayout);
        jPanelBackplateLayout.setHorizontalGroup(
            jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackplateLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackplateLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(lblCreateAReview))
                    .addGroup(jPanelBackplateLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblGame, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRating)
                            .addComponent(lblComment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGame, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelBackplateLayout.createSequentialGroup()
                                    .addComponent(cmbPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(jPanelBackplateLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(btnPostReview, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHelp)
                    .addGroup(jPanelBackplateLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblHelp)))
                .addGap(47, 47, 47))
        );
        jPanelBackplateLayout.setVerticalGroup(
            jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackplateLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateAReview, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGame, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGame))
                .addGap(18, 18, 18)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlatform))
                .addGap(18, 18, 18)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComment)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelBackplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackplateLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnPostReview, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackplateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelp)
                        .addGap(9, 9, 9)
                        .addComponent(lblHelp)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        new addGame().setVisible(true); //open new game screen.
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new Main(uID).setVisible(true); //return to main screen
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPostReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostReviewActionPerformed
        //Creating a new review 
        
        //get the current date and time
        DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        Date dateObj = new Date();
        
        
        //insert values from "create review" screen into database
        //get inputted data
        String gameInput = (String)cmbGame.getSelectedItem();
        String platformInput = (String)cmbPlatform.getSelectedItem();
        int rating = Integer.parseInt(((String)cmbRating.getSelectedItem()));
        String comment = txaComment.getText();
           
        if (gameInput == "(Not selected)") //validates that a game is selected
        {
            JOptionPane.showMessageDialog(null, "Please select a game and try again.");
            return;
        }
           
        for (int i = 0; i<fullSize; i++) //loop through game array to find the array element with the GameName and Platform that matches the user's input (will need the game id for review table)
        {
            if(gameInput.equals(fullArray[i].getName()) && platformInput.equals(fullArray[i].getPlatform()))
            {
                int gID = fullArray[i].getNumber(); //get that game's ID
                
                
                //Send variables to SQLSTatments class to add review to the database
                SQLSTatements aa = new SQLSTatements();
                aa.InsertReview(uID, gID, rating, comment);
                new Main(uID).setVisible(true);
                this.dispose(); //close this screen after review added to database
                return;
            }
        }
        
        //If the game and platform do not match (didn't find a )display an error message with help information.
        JOptionPane.showMessageDialog(null, "The game: '"+gameInput+"' does not appear to be available on "+platformInput+". Try again OR Click 'Add a game' to add the new version of the game to Fire reviews.");
        
    }//GEN-LAST:event_btnPostReviewActionPerformed

    private void cmbRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRatingActionPerformed

    private void cmbGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGameActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        //Create help box (using message number 7)
        Help h = new Help(7);
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createReview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnPostReview;
    private javax.swing.JComboBox<String> cmbGame;
    private javax.swing.JComboBox<String> cmbPlatform;
    private javax.swing.JComboBox<String> cmbRating;
    private javax.swing.JPanel jPanelBackplate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblCreateAReview;
    private javax.swing.JLabel lblGame;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JLabel lblRating;
    private javax.swing.JTextArea txaComment;
    // End of variables declaration//GEN-END:variables
}
