/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package powernotes.pat;

/**
 *
 * @author maim20
 */
public class homeScreen extends javax.swing.JFrame {

    /**
     * Creates new form homeScreen
     */
    public homeScreen() {
        initComponents();
        
        //hide picture and text initially (lblFireIgnite is visible)
        this.setVisible(true);
        lblFire.setVisible(false);
        lblIgnite.setVisible(false);
        
        int i = 1;
        
        if (i==1) //wait 3 seconds
        {
            try
            {
                Thread.sleep(3000);
            }
            catch (InterruptedException ie)
            {
                
            }
        }
        
        lblFire.setVisible(true); //change the flame image to another flame image; little animation
        lblFireIgnite.setVisible(false);
        lblIgnite.setVisible(true);
        
        if (i==1) //wait another 1,2 seconds
        {
            try 
            {
                Thread.sleep(1200);
            }
            catch (InterruptedException ie)
            {
                
            }
        }
        
        new loginScreen().setVisible(true); //open login screen
 
        this.setVisible(false); //close this screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        txfLoading = new javax.swing.JLabel();
        lblFireIgnite = new javax.swing.JLabel();
        lblFire = new javax.swing.JLabel();
        lblIgnite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfLoading.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        txfLoading.setText("Loading Fire Reviews");
        txfLoading.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 3, true));
        getContentPane().add(txfLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 510, 150));
        txfLoading.setHorizontalAlignment(txfLoading.CENTER);

        lblFireIgnite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/powernotes/pat/fire_ignite.png"))); // NOI18N
        getContentPane().add(lblFireIgnite, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 130, 150));

        lblFire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/powernotes/pat/fire.png"))); // NOI18N
        getContentPane().add(lblFire, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 130, 150));

        lblIgnite.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblIgnite.setText("*Fwwaaaa*");
        getContentPane().add(lblIgnite, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFire;
    private javax.swing.JLabel lblFireIgnite;
    private javax.swing.JLabel lblIgnite;
    private javax.swing.JLabel txfLoading;
    // End of variables declaration//GEN-END:variables


}
