/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package powernotes.pat;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javafx.application.Platform.exit;

/**
 *
 * @author Maxwell SSD
 */
public class Main extends javax.swing.JFrame {
    
    private GameArray ga = new GameArray(); //create GameArray object
    private Game[] gArray = ga.getDistArray(); //get array of distinct game names
    private int gSize = ga.getDistSize();//get size of this array
    
    private Game[] fullArray = ga.getgArray(); //get array of all games
    private int fullSize = ga.getSize(); //get size of this array
    private int uID;
    
    private ReviewArray ra = new ReviewArray(); //create ReviewArray object
    private Review[] rArray = ra.getrArray(); //get array of reviews
    private int rSize = ra.getSize(); //get size of this array
    
    //variables for the selection of the filter components by the user.
    private String gameSortSelected;
    private String platformSortSelected;
    private String gameSort;
    private String platformSort;
    private String usernameSort;
    
    private boolean admin = false; //user is not admin. If they are it will be changed later in the program.
    //This makes sure users don't get admin privileges by mistake.


    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        jPanelAdminTools.setVisible(false);
        txaDisplay.setText(ra.toString()); //display reviews
        for (int i = 0; i < gSize; i++)
        {
            cmbGame.addItem(gArray[i].getName()); //populate game combo box
            cmbGameDelete.addItem(gArray[i].getName()); //populate game combo box
        }
    }
    

    public Main(int u) //
    { 
        uID = u;
            
        initComponents();
        jPanelAdminTools.setVisible(false);
        txaDisplay.setText(ra.toString()); //display reviews
        for (int i = 0; i < gSize; i++)
        {
            cmbGame.addItem(gArray[i].getName()); //populate game combo box
            cmbGameDelete.addItem(gArray[i].getName()); //populate game combo box
        }
        
        UserArray uArr = new UserArray(uID);
        admin = uArr.getAdminStatus(); //get the boolean for user admin status
        

        btnAdminTools.setVisible(admin); //allow admins to access the Admin Tools button
    }
    
    //sort
    public Main(int u, String gameIn, String platformIn, String usernameIn) //accepts the parameters that need to be filered by
    {
        uID = u;
           
        initComponents();
        jPanelAdminTools.setVisible(false);
        
        //display reviews
        txaDisplay.setText(ra.toStringSort(gameIn, platformIn, usernameIn)); //filter according to parameters. ReviewArray object will return the sorted reviews as a string
        
        
        for (int i = 0; i < gSize; i++)
        {
            cmbGame.addItem(gArray[i].getName()); //populate game combo box
            cmbGameDelete.addItem(gArray[i].getName()); //populate game combo box
        }
        
        UserArray uArr = new UserArray(uID);
        admin = uArr.getAdminStatus(); //get the boolean for user admin status
        
        btnAdminTools.setVisible(admin); //allow admins to access the Admin Tools button
    }
    
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelBackplate = new javax.swing.JPanel();
        jPanelTopBanner = new javax.swing.JPanel();
        btnAdminTools = new javax.swing.JButton();
        btnCreateReview = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jPanelLeftBanner = new javax.swing.JPanel();
        lblSort = new javax.swing.JLabel();
        lblGame = new javax.swing.JLabel();
        cmbPlatform = new javax.swing.JComboBox<>();
        lblPlatform = new javax.swing.JLabel();
        cmbGame = new javax.swing.JComboBox<>();
        txfUsername = new javax.swing.JTextField();
        btnSort = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblHelp = new javax.swing.JLabel();
        jPanelRightBanner = new javax.swing.JPanel();
        jPanelDisplay = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        txaDisplay = new javax.swing.JTextArea();
        jPanelAdminTools = new javax.swing.JPanel();
        lblAdminTools = new javax.swing.JLabel();
        btnBackToMain = new javax.swing.JButton();
        cmbGameDelete = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        lblHelpAdminTools = new javax.swing.JLabel();
        btnHelpAdminTools = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBackplate.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackplate.setMaximumSize(new java.awt.Dimension(1600, 900));
        jPanelBackplate.setMinimumSize(new java.awt.Dimension(1600, 900));
        jPanelBackplate.setPreferredSize(new java.awt.Dimension(1600, 900));
        jPanelBackplate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopBanner.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTopBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminTools.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnAdminTools.setText("Admin tools");
        btnAdminTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminToolsActionPerformed(evt);
            }
        });
        jPanelTopBanner.add(btnAdminTools, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 50, 237, 58));

        btnCreateReview.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        btnCreateReview.setText("Create a review");
        btnCreateReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReviewActionPerformed(evt);
            }
        });
        jPanelTopBanner.add(btnCreateReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 240, 60));

        btnExit.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnExit.setText("Logout and exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanelTopBanner.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 80, 150, 33));

        btnLogout.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanelTopBanner.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 40, 150, 33));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/powernotes/pat/fire.png"))); // NOI18N
        jPanelTopBanner.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 140));

        lblTitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 48)); // NOI18N
        lblTitle.setText("Fire reviews");
        jPanelTopBanner.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 220, 94));

        jPanelBackplate.add(jPanelTopBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 160));

        jPanelLeftBanner.setBackground(new java.awt.Color(100, 145, 213));
        jPanelLeftBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSort.setFont(new java.awt.Font("Dubai Medium", 1, 40)); // NOI18N
        lblSort.setText("Filter");
        jPanelLeftBanner.add(lblSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        lblGame.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lblGame.setText("Game");
        jPanelLeftBanner.add(lblGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        cmbPlatform.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        cmbPlatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any Platform", "PC", "XBOX", "PS4", "Nintendo", "Mobile" }));
        cmbPlatform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlatformActionPerformed(evt);
            }
        });
        jPanelLeftBanner.add(cmbPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 40));

        lblPlatform.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lblPlatform.setText("Platform");
        jPanelLeftBanner.add(lblPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        cmbGame.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        cmbGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Games" }));
        cmbGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGameActionPerformed(evt);
            }
        });
        jPanelLeftBanner.add(cmbGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 40));

        txfUsername.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });
        jPanelLeftBanner.add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 240, 40));

        btnSort.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnSort.setText("Apply Filter");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        jPanelLeftBanner.add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 190, 50));

        lblUsername.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lblUsername.setText("Username");
        jPanelLeftBanner.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        btnHelp.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanelLeftBanner.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, -1, -1));

        lblHelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHelp.setText("Help");
        jPanelLeftBanner.add(lblHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 710, -1, -1));

        jPanelBackplate.add(jPanelLeftBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 390, 740));

        jPanelRightBanner.setBackground(new java.awt.Color(100, 145, 213));
        jPanelRightBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBackplate.add(jPanelRightBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 160, 20, 740));

        jPanelDisplay.setBackground(new java.awt.Color(60, 109, 188));

        txaDisplay.setEditable(false);
        txaDisplay.setColumns(20);
        txaDisplay.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txaDisplay.setRows(5);
        txaDisplay.setAutoscrolls(false);
        jScrollPane.setViewportView(txaDisplay);

        jPanelAdminTools.setBackground(new java.awt.Color(255, 255, 255));

        lblAdminTools.setFont(new java.awt.Font("Dubai Medium", 0, 40)); // NOI18N
        lblAdminTools.setText("Admin tools - Remove games");

        btnBackToMain.setText("Back");
        btnBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainActionPerformed(evt);
            }
        });

        cmbGameDelete.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        cmbGameDelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No game selected" }));

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Remove the selected game from the database");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblHelpAdminTools.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHelpAdminTools.setText("Help");

        btnHelpAdminTools.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnHelpAdminTools.setText("?");
        btnHelpAdminTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpAdminToolsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminToolsLayout = new javax.swing.GroupLayout(jPanelAdminTools);
        jPanelAdminTools.setLayout(jPanelAdminToolsLayout);
        jPanelAdminToolsLayout.setHorizontalGroup(
            jPanelAdminToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminToolsLayout.createSequentialGroup()
                .addGroup(jPanelAdminToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminToolsLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(cmbGameDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAdminToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdminToolsLayout.createSequentialGroup()
                            .addGap(465, 465, 465)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelAdminToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblHelpAdminTools, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHelpAdminTools)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdminToolsLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btnBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(288, 288, 288)
                            .addComponent(lblAdminTools))))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanelAdminToolsLayout.setVerticalGroup(
            jPanelAdminToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminTools, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addComponent(cmbGameDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(jPanelAdminToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdminToolsLayout.createSequentialGroup()
                        .addComponent(btnHelpAdminTools, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHelpAdminTools)))
                .addGap(153, 153, 153))
        );

        javax.swing.GroupLayout jPanelDisplayLayout = new javax.swing.GroupLayout(jPanelDisplay);
        jPanelDisplay.setLayout(jPanelDisplayLayout);
        jPanelDisplayLayout.setHorizontalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdminTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDisplayLayout.setVerticalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdminTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBackplate.add(jPanelDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 1490, 740));

        getContentPane().add(jPanelBackplate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //close program
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose(); //return to login screen
        new loginScreen().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAdminToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminToolsActionPerformed
        //Go to admin tools panel
        jScrollPane.setVisible(false);
        jPanelAdminTools.setVisible(true);
    }//GEN-LAST:event_btnAdminToolsActionPerformed

    private void btnBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainActionPerformed
        //Go to main screen
        new Main(uID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackToMainActionPerformed

    private void btnCreateReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReviewActionPerformed
        //Go to create review screen
        new createReview(uID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateReviewActionPerformed

    private void cmbPlatformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlatformActionPerformed
        
    }//GEN-LAST:event_cmbPlatformActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        //Create help box (using message number 3)
        Help h = new Help(3);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        //Filter

        //Collect the sort parameters (filter)
        gameSortSelected = (String)cmbGame.getSelectedItem();
        platformSortSelected = (String)cmbPlatform.getSelectedItem();
        usernameSort = txfUsername.getText();
        
        //Set the variables to null if the default item is selected (therefore, don't want to sort by that category)
        if(!gameSortSelected.equals("All Games"))
            gameSort = gameSortSelected;
        else
            gameSort = "";
        
        if(!platformSortSelected.equals("Any Platform"))
            platformSort = platformSortSelected;
        else
            platformSort = "";
        

        //Send the filter parameters (and userID because we don't want to lose it) to a new Main class and dispose of this one
        new Main(uID, gameSort, platformSort, usernameSort).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSortActionPerformed

    private void cmbGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGameActionPerformed
        
    }//GEN-LAST:event_cmbGameActionPerformed

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed
        
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //Delete a game from the database AND delete all reviews made about that game
        
        String gameToDelete = (String)cmbGameDelete.getSelectedItem();
        int gameToDeleteID = 1000000000; //initialise integer in such a way that if the ID is not collected properly, an SQL error will occur, preventing the wrong game and reviews being deleted
        
        for(int i = 0; i<fullSize; i++) //loop through game array to find the GameID of selected game
        {
            if(fullArray[i].getName().equals(gameToDelete))
            {
                gameToDeleteID = fullArray[i].getNumber(); //get the game id
            }
        }
        
        //use SQLSTastements object to delete the game and reviews including the game
        SQLSTatements dd = new SQLSTatements();
        dd.deleteGame(gameToDelete, gameToDeleteID);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnHelpAdminToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpAdminToolsActionPerformed
        //Create help box (using message number 5)
        Help h = new Help(5);
    }//GEN-LAST:event_btnHelpAdminToolsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminTools;
    private javax.swing.JButton btnBackToMain;
    private javax.swing.JButton btnCreateReview;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHelpAdminTools;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSort;
    private javax.swing.JComboBox<String> cmbGame;
    private javax.swing.JComboBox<String> cmbGameDelete;
    private javax.swing.JComboBox<String> cmbPlatform;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelAdminTools;
    private javax.swing.JPanel jPanelBackplate;
    private javax.swing.JPanel jPanelDisplay;
    private javax.swing.JPanel jPanelLeftBanner;
    private javax.swing.JPanel jPanelRightBanner;
    private javax.swing.JPanel jPanelTopBanner;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAdminTools;
    private javax.swing.JLabel lblGame;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblHelpAdminTools;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JLabel lblSort;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextArea txaDisplay;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
